# 파일의 규격에 따라 지원하는 옵션이 달라지며, 최근에 "3.1"이 등장하긴 했지만 보통은 "2"나 "2.1"을 사용해도 충분합니다.
version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
       - "80:80"
    volumes:
      - .:/code
      - ./config/nginx2/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
volumes:
  django_api: {}
