# 파일의 규격에 따라 지원하는 옵션이 달라지며, 최근에 "3.1"이 등장하긴 했지만 보통은 "2"나 "2.1"을 사용해도 충분합니다.
version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
       - "80:80"
    volumes:
      - .:/code
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  # ALLOWED HOSTS에 web을 추가해줘야함
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -c mysite/gunicorn_cfg.py mysite.wsgi:application --bind 0.0.0.0:8000
#     gunicorn -c mysite/gunicorn_cfg.py mysite.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - .:/code

#    expose:
#      - "8000"
#      -
    ports:
      - "8000:8000"
volumes:
  django_api: {}